version: "2.1"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile in the server directory
    command: "npm run start"
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3001:3000"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    command: "npm start"
    volumes:
      - ./client/src:/usr/src/app/client/src
      - ./client/public:/usr/src/app/client/public
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server
    stdin_open: true

